---
name: KMP library compilation check
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build-library:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Check
        run: ./local-check.sh
      - name: Plugin local publish
        run: ./gradlew -p resources-generator publishToMavenLocal
      - name: Library local publish
        run: ./gradlew publishToMavenLocal
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-android-mpp-app:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - android-mpp-app
        run: cd samples/android-mpp-app && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-auto-manifest:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - auto-manifest
        run: cd samples/auto-manifest && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-compose-jvm-app:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - compose-jvm-app
        run: cd samples/compose-jvm-app && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-resources-gallery:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - resources-gallery
        run: cd samples/resources-gallery && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-default-hierarchy-resources-gallery-mobile:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - default-hierarchy-gallery-mobile
        run: cd samples/default-hierarchy-gallery-mobile && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-ios-static-xcframework:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - ios-static-xcframework
        run: cd samples/ios-static-xcframework && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-kotlin-ios-app:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - kotlin-ios-app
        run: cd samples/kotlin-ios-app && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
  check-sample-compose-resources-gallery:
    runs-on: macOS-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref !=
            'refs/heads/develop' }}
      - name: Cache .konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', 'gradle/**/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Download maven artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/dev/icerock
      - name: Sample - compose-resources-gallery
        run: cd samples/compose-resources-gallery && ./local-check.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: "**/build/test-results/**/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ github.job }}
          path: "**/build/reports/**/*"
