name: KMP library compilation check

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Plugin check
        run: ./gradlew -p resources-generator build publishToMavenLocal
      - name: check android only build
        run: ./gradlew clean assembleDebug
      - name: check jvm only build
        run: ./gradlew clean jvmJar
      - name: check ios only build
        run: ./gradlew clean compileKotlinIosX64
      - name: Library check
        run: ./gradlew build publishToMavenLocal
      - name: Check custom samples
        run: cd sample/clean-compose-jvm-app && ./gradlew build
      - name: Install pods
        run: cd sample/ios-app && pod install
      - name: Check iOS
        run: cd sample/ios-app && set -o pipefail && xcodebuild -scheme TestProj -workspace TestProj.xcworkspace -configuration Debug -sdk iphonesimulator -arch x86_64 build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty
